# -*- coding: utf-8 -*-

import importlib
import importlib.util
import os
import setuptools

"""This file is used to package the StockHistory plugin.

- It was generated by the InvenTree Plugin Creator tool - version 1.6.0
- Ref: https://github.com/inventree/plugin_creator
"""

"""Read the plugin version from the source code."""
module_path = os.path.join(os.path.dirname(__file__), "stock_history", "__init__.py")
spec = importlib.util.spec_from_file_location("stock_history", module_path)
stock_history = importlib.util.module_from_spec(spec)
spec.loader.exec_module(stock_history)

with open("README.md", encoding="utf-8") as f:
    long_description = f.read()

setuptools.setup(
    name="inventree-stock-history",
    version=stock_history.PLUGIN_VERSION,
    author="Oliver Walters",
    author_email="oliver.henry.walters@gmail.com",
    description="Record historical stock levels",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/inventree/inventree-stock-history",
    license="MIT",
    packages=setuptools.find_packages(),
    keywords="inventree plugin",
    include_package_data=True,
    install_requires=[
        # Enter your plugin library dependencies here
    ],
    setup_requires=[
        "wheel",
        "twine",
    ],
    python_requires=">=3.9",
    entry_points={
        "inventree_plugins": ["StockHistory = stock_history.core:StockHistory"]
    },
)
