# Generated by Django 4.2.22 on 2025-06-24 12:59

import InvenTree.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("part", "0135_alter_part_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockHistoryEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_count",
                    models.IntegerField(
                        default=1,
                        help_text="Number of individual stock items",
                        verbose_name="Item Count",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Total available stock quantity",
                        max_digits=19,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date of stock count",
                        verbose_name="Date",
                    ),
                ),
                (
                    "cost_min_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[], default="", editable=False, max_length=3, null=True
                    ),
                ),
                (
                    "cost_min",
                    InvenTree.fields.InvenTreeModelMoneyField(
                        blank=True,
                        currency_choices=[],
                        decimal_places=6,
                        default_currency="",
                        help_text="Estimated minimum cost of stock on hand",
                        max_digits=19,
                        null=True,
                        validators=[djmoney.models.validators.MinMoneyValidator(0)],
                        verbose_name="Minimum Stock Cost",
                    ),
                ),
                (
                    "cost_max_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[], default="", editable=False, max_length=3, null=True
                    ),
                ),
                (
                    "cost_max",
                    InvenTree.fields.InvenTreeModelMoneyField(
                        blank=True,
                        currency_choices=[],
                        decimal_places=6,
                        default_currency="",
                        help_text="Estimated maximum cost of stock on hand",
                        max_digits=19,
                        null=True,
                        validators=[djmoney.models.validators.MinMoneyValidator(0)],
                        verbose_name="Maximum Stock Cost",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_history_entries",
                        to="part.part",
                        verbose_name="Part",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock History Entry",
                "verbose_name_plural": "Stock History Entries",
            },
        ),
    ]
